- type: job
  id: Prosecutor
  name: job-name-prosecutor
  description: job-description-prosecutor
  playTimeTracker: JobProsecutor
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 36000 # 10 hrs
    - !type:CharacterEmployerRequirement
      employers:
      - NanoTrasen
  startingGear: ProsecutorGear
  icon: "JobIconProsecutor"
  supervisors: job-supervisors-cj
  access:
  - Prosecutor
  - Justice
  - Security
  - Maintenance

- type: startingGear
  id: ProsecutorGear
  subGear:
  - PassengerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitProsecutor
    neck: ClothingNeckProsecutorbadge
    back: ClothingBackpackLawyerFilled
    shoes: ClothingShoesBootsLaceup
    id: ProsecutorPDA
    ears: ClothingHeadsetJustice # Pirate
  inhand:
    - BriefcaseBrownFilled
    - BookSecurity # Pirate
  innerClothingSkirt: ClothingUniformJumpskirtProsecutor
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled


